# Generated by Django 4.2.6 on 2023-10-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_overview_teammember_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
