# Generated by Django 4.2.6 on 2023-10-19 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_overview_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Overview',
            new_name='Project',
        ),
    ]
